### ISSUE TITLE
Install from the current author's repository

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/astyle#1]
```bash
git clone https://gitlab.com/saalen/astyle.git astyle
cd astyle/
git checkout "$(git describe --tags "$(git rev-list --tags --max-count=1)")"
cd AStyle/build/gcc/
```

https://sourceforge.net/projects/astyle/files/astyle/

**Comment by szepeviktor** [comment]
```yaml
      -
        name: Checkout astyle
        uses: actions/checkout@v4
        with:
            repository: szepeviktor/astyle
            path: astyle
      -
        name: Install astyle
        run: |
            cd astyle/build/gcc/
            make
            sudo make install
            astyle --version
```
